# Generated by Django 4.2.7 on 2023-12-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='blog_images/')),
            ],
        ),
    ]
