# Generated by Django 4.2.7 on 2023-12-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='blog_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
