# Generated by Django 4.2.7 on 2023-12-09 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogtables_delete_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtables',
            name='order_number',
        ),
    ]
