# Generated by Django 4.2.7 on 2023-12-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_remove_blogtables_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtables',
            name='photo',
        ),
        migrations.AddField(
            model_name='blogtables',
            name='order_number',
            field=models.IntegerField(default=0),
        ),
    ]
