# Generated by Django 4.2.7 on 2023-12-11 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_blogtables_photo_blogtables_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtables',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogtables',
            name='ImageField',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
