# Generated by Django 4.2.7 on 2023-12-13 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_remove_blogtables_imagefield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtables',
            name='Created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
