# Generated by Django 4.2.7 on 2023-12-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blogtables_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtables',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
