# Generated by Django 4.2.7 on 2023-12-14 07:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_alter_blogtables_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtables',
            name='ImageField',
            field=models.ImageField(default='image/abc.png', upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogtables',
            name='Created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
