# Generated by Django 4.2.7 on 2023-12-15 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_blogtables_imagefield_alter_blogtables_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtables',
            name='ImageField',
        ),
        migrations.AddField(
            model_name='blogtables',
            name='imageField',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image/'),
            preserve_default=False,
        ),
    ]
